export const directorBiography = {
  name: "Alassana Mara",
  role: "Ingénieur, entrepreneur, engagé pour l’intégration et la transmission.",
  paragraphs: [
    "Je m’appelle Alassana Mara, ingénieur spécialisé en Metallbau et Konstruktionstechnik, installé en Allemagne depuis 2018. Mon parcours est celui d’un homme qui a choisi de construire : construire des structures, des projets et des entreprises, mais aussi construire des ponts entre les cultures, les générations et les personnes.",
    "Lorsque je suis arrivé en Allemagne, j’ai découvert un environnement entièrement nouveau. Je ne connaissais pas encore suffisamment la langue, le fonctionnement du système, les démarches administratives ni les codes sociaux et professionnels du pays. Comme beaucoup de personnes qui arrivent dans un nouvel environnement, j’ai dû apprendre à comprendre, à m’adapter et à trouver progressivement ma place.",
    "Cette période m’a appris une chose essentielle : l’intégration ne se décrète pas, elle se construit.",
    "À partir de 2020, j’ai commencé mes formations de base avec une ambition claire : bâtir une carrière solide dans le domaine de la construction métallique. Ce parcours m’a demandé de la discipline, de la rigueur, de la précision et beaucoup de persévérance. Le métier m’a également enseigné une valeur qui dépasse largement le cadre professionnel : la patience.",
    "Dans la construction métallique, une structure solide ne repose jamais sur un seul élément. Chaque pièce doit trouver sa place, chaque mesure doit être précise et chaque étape doit être réalisée avec sérieux. Avec le temps, j’ai compris que la vie ressemble parfois à une construction : ce sont les efforts réguliers, souvent invisibles, qui permettent finalement d’ériger quelque chose de durable.",
    "Aujourd’hui, je suis fier du chemin parcouru dans le domaine de l’ingénierie et de la construction. Ce parcours représente pour moi bien plus qu’une réussite professionnelle. Il est la preuve qu’avec du travail, de la persévérance, de la formation et de la confiance en soi, il est possible de transformer une situation de départ difficile en une véritable trajectoire d’avenir.",
    "Mais mon engagement ne s’arrête pas à mon métier.",
    "Je suis également impliqué dans la vie associative et communautaire. En tant que président de plusieurs associations, notamment USJDK, je participe à des initiatives orientées vers la jeunesse, la solidarité, la responsabilité collective et le développement communautaire.",
    "Je dirige par ailleurs Mara & Frères Import-Export, une entreprise familiale qui contribue à créer des liens économiques et commerciaux entre l’Europe et l’Afrique. À travers cette activité, je retrouve une autre dimension essentielle de mon parcours : celle du lien entre les territoires, les cultures et les opportunités.",
    "En 2023, une nouvelle étape importante a commencé.",
    "Fort de ma propre expérience d’intégration, j’ai décidé de consacrer une partie de mon temps à l’accompagnement des personnes immigrées. Mon engagement est volontaire et repose sur une conviction simple : personne ne devrait être condamné à rester seul face aux difficultés de son parcours.",
    "J’accompagne notamment des personnes qui souhaitent comprendre leur environnement, améliorer leurs connaissances de base, trouver une formation ou identifier les premières étapes nécessaires à leur insertion professionnelle.",
    "J’organise également des conférences et des rencontres autour des questions de migration, d’intégration, de formation et d’avenir professionnel.",
    "Au fil de ces rencontres, j’ai découvert une réalité qui me touche particulièrement : derrière chaque dossier administratif, chaque demande de formation ou chaque difficulté linguistique, il y a une personne, une famille, des responsabilités et souvent beaucoup d’espoir.",
    "Je rencontre des parents qui élèvent un, deux ou trois enfants et qui ont parfois le sentiment d’avoir pris du retard dans leur vie. Certains doutent de leurs capacités. D’autres ont peur de recommencer à zéro. Beaucoup se demandent s’il est encore possible de construire quelque chose de solide dans un pays qu’ils connaissent encore mal.",
    "À ces personnes, je veux transmettre un message que mon propre parcours m’a appris : il n’est jamais trop tard pour apprendre, recommencer et construire.",
    "L’intégration est rarement un chemin rapide. Elle demande du temps, de la volonté, de l’humilité et parfois la capacité d’accepter de repartir de zéro. Mais chaque compétence acquise, chaque mot appris, chaque démarche accomplie et chaque difficulté surmontée constitue une pierre supplémentaire dans la construction d’un avenir meilleur.",
    "C’est cette philosophie qui guide aujourd’hui mon engagement.",
    "Je souhaite redonner confiance à ceux qui doutent, transmettre des connaissances à ceux qui cherchent leur voie, ouvrir des portes à ceux qui ne savent pas encore où frapper et encourager ceux qui ont décidé d’avancer malgré les difficultés.",
    "Je crois profondément que chaque personne mérite une opportunité de progresser. Je crois également que la réussite ne se mesure pas uniquement aux diplômes, au statut professionnel ou aux biens que l’on possède. Elle se mesure aussi à notre capacité à nous relever, à apprendre, à aider les autres et à laisser derrière nous quelque chose de positif.",
    "Mon parcours entre l’Afrique et l’Europe, entre l’ingénierie, l’entrepreneuriat, le monde associatif et l’accompagnement des personnes, m’a progressivement conduit vers une conviction : construire pour soi est important, mais construire pour les autres donne un sens plus profond à ce que l’on accomplit.",
    "Aujourd’hui, je continue donc à construire.",
    "Je construis des projets, des entreprises, des opportunités et des espaces de dialogue. Je construis également des passerelles entre ceux qui arrivent et ceux qui sont déjà installés, entre les générations, entre les cultures et entre les ambitions individuelles et les besoins de la communauté.",
    "Mon histoire n’est pas celle d’un parcours parfait. C’est celle d’un homme qui a dû apprendre, s’adapter, travailler, persévérer et continuer à avancer.",
    "Et si mon parcours peut transmettre une seule chose, c’est celle-ci : on peut partir de loin sans être condamné à rester loin de ses rêves.",
    "Chaque étape compte. Chaque effort compte. Chaque rencontre peut ouvrir une porte.",
    "La réussite n’est pas une course. C’est une construction.",
  ],
};
